### ISSUE TITLE
Correct entrypoint for procedures

### ISSUE THREAD

**Issue by jacobeatsspam** [DanCardin/sqlalchemy-declarative-extensions#81]
I'm working with procedures (with mysql/mariadb) and its not clear to me how to best register them.

Can you help clarify? And maybe explain why there isn't a decorator similar to `view()`? I notice that all the other declarative types like a similar decorator...

As far as I can tell, registration of procedures must be done manually or using `declare_database`?

**Comment by DanCardin** [comment]
For everything that's not views (but also for views, if you just write raw sql) registration is done through `declarative_database` or `declare_database`.

```python
from sqlalchemy_declarative_extensions import declare_database, declarative_database, Procedures
from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

procedures = [Procedure(...)]

@declarative_database
class Base(DeclarativeBase):
    procedures = procedures

# or
metadata = MetaData()
...
declare_database(metadata, procedures=procedures)
```

Views are somewhat unique in that they **can** be dependent upon sqlalchemy table/models being defined, so that you can use them to produce queries. That creates a circular dependency on the MetaData that doesn't exist for any of the other object types.

Also views, like tables, can be defined as classes that get instantiated by queries. Similarly, this doesn't really apply to other object types.

**Comment by jacobeatsspam** [comment]
@DanCardin Thanks for the breakdown, this is helpful. Two follow up questions
- I ended up using `register_procedure(Base, Procedure())`, instead of playing with `declarative_database`. Is there any reason to prefer one approach over the other?
- As you can probably imagine, for mysql, I ended up hitting the `NotImplemented` error since the dialect doesn't have support for procedures yet. Are there any things to consider or keep in mind as I seek to add support for procedures for mysql?

**Comment by DanCardin** [comment]
Nope, `register_procedure` works, you'd just need to manually register each individual procedure versus it being done for you. All this does it append it to the list of procedures on the metadata for you, which is enough for alembic.

If you're willing/able to contribute, it'd be a matter of implementing these [missing functions](https://github.com/DanCardin/sqlalchemy-declarative-extensions/blob/main/src/sqlalchemy_declarative_extensions/dialects/query.py#L110) for the relevant codepaths for you/mysql, which basically amounts to determining the necessary queries in mysql to introspect the details about the procedures. you'd also likely need to implement a mysql-specific procedure [subclass like the postgres one](https://github.com/DanCardin/sqlalchemy-declarative-extensions/blob/main/src/sqlalchemy_declarative_extensions/dialects/postgresql/procedure.py), since i assume there's going to be small interdialect-specific syntax/option differences.

I thought I had provisional support for this in mysql, but I suppose i dont 😬. I'm happy to look into it, but i might not get to it in your timeline. lmk if you want to start working on it, so i know not to :D

**Comment by jacobeatsspam** [comment]
Haha, yeah I already started working on a branch. It's working well so far. I'll open a draft PR for your review soon.
